### ISSUE TITLE
matplotlib not installed as dependency via pip

### ISSUE THREAD

**Issue by bhughes339** [RDML-consortium/rdmlpython#8]
Looks like the other dependencies (`lmxl`, `scipy`, `numpy`) are correctly installed, but `matplotlib` is not.

After running `pip3 install rdmlpython` in a fresh virtual environment:

```
>>> import rdmlpython
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/williamhughes/rdmlpython/__init__.py", line 3, in <module>
    from .rdml import *
  File "/Users/williamhughes/rdmlpython/rdml.py", line 20, in <module>
    from matplotlib.backends.backend_svg import FigureCanvasSVG as figSVG
ModuleNotFoundError: No module named 'matplotlib'
```

**Comment by untergasser** [comment]
Hi,

thank you for pointing it out. I included it now, so it should work.

Best,
Andreas
